//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public string imageURL { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string movieCategory { get; set; }
        public Nullable<int> cinemaID { get; set; }
        public Nullable<int> producerID { get; set; }
        public Nullable<int> actorID { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Actor Actor { get; set; }
    }
}
